name: flutter_ui_challenges
description: UI challenges, animations and more!
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  animations: ^2.0.3
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.0
  go_router: ^4.0.0
  video_player: ^2.4.5

dev_dependencies:
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.3.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/netflix_clone/

flutter_gen:
  output: lib/generated/
  line_length: 80
  null_safety: true

  integrations:
    flutter_svg: true

  assets:
    enabled: true
